apply:
  label: Apply
  to: https://forms.gle/UesbK7kDtXVzjMGc9
  target: _blank
available: false
colorHex: "#da1309"
description: Join The PITP Help Team and help us manage our events! At our frontline you will help us in running our community events!
details:
  duties:
    - Help with queue and crowd flow
    - Provide directions and basic information
    - Escalate issues to Team Leaders
  contactEmail: volunteer@pupsinthepark.org
  requirements:
    - Be over 18
    - Able to work as a team
    - Have Good problem mitigation skills
icon: i-lucide-users
name: Helper
