apply:
  label: Check Eligibility
  to: https://forms.gle/steward-form
  target: _blank
available: true
colorHex: "#dbc226"
description: Are you a Content Creator in our community? Partner with PITP!
details:
  duties: []
  contactEmail: events@pupsinthepark.org
  requirements:
    - Have 50k+ Followers on any Platform
    - Actively Create content for a kemonomimi / furry / alterhuman / therian audience
    - ""
icon: i-lucide-instagram
name: Content Creator
