apply:
  label: Apply
  to: https://forms.gle/EVF1ZE9YiCpsvNWS7
  target: _blank
available: false
colorHex: "#373c44"
description: Join The PITP Event Operations team and help us manage our events! A leading position at our frontline. Experiance in team leadership required.
details:
  duties:
    - Help with queue and crowd flow
    - Provide directions and basic information
    - Escalate issues to Event Management
  contactEmail: volunteer@pupsinthepark.org
  requirements:
    - Have prior experience in team leadership
    - Be over 18
    - Able to direct a team
icon: i-lucide-users
name: Team Lead
